language: ruby
rvm:
- 2.2.2
- 2.3.0
- 2.4.0
gemfile:
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
cache:
  bundler: true
script:
  - bundle exec rake db:create
  - bundle exec rake spec
notifications:
  webhooks:
    secure: QFW4WHH8A/ht3EKFbUNc7u03Ca+P6qm7ypIiXU+y8fO8fEps2/f7fTrWIUGkohShFyaaZw1/NjDWUx86LYBFfs4dYduHy8U3BSbWrS4ot4+oO9TsKdatKydTXpbvRqjgPITECmMWDoz4e7gMdZ5fGuBBdO1LQGVRr9mUXl13QU4=
